// File generated by FlutterFire CLI. Run: dart run flutterfire_cli:flutterfire configure
// Or copy your web config from Firebase Console > Project settings > Your apps

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQGYPhJ3GODFJOcnmENX6GGTObvUBLEI',
    appId: '1:280920543254:web:43339b6e17abf8e95b2537',
    messagingSenderId: '280920543254',
    projectId: 'goroady-22332',
    authDomain: 'goroady-22332.firebaseapp.com',
    storageBucket: 'goroady-22332.firebasestorage.app',
  );

}