// File generated by FlutterFire Configure.
// Run: dart run flutterfire_cli:flutterfire configure
// Then replace the placeholder values below with your Firebase project's web config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDxQGYPhJ3GODFJOcnmENX6GGTObvUBLEI",
    authDomain: "goroady-22332.firebaseapp.com",
    projectId: "goroady-22332",
    storageBucket: "goroady-22332.firebasestorage.app",
    messagingSenderId: "280920543254",
    appId: "1:280920543254:web:43339b6e17abf8e95b2537"
  );
}
